// Generated by https://quicktype.io

export interface Paquetes {
  paquetes: Paquete[];
}

export interface Paquete {
  id?:              number;
  numero_de_guia:   string;
  paqueteria:       string;
  quien_captura:    string;
  usuario:          string;
  correo:           string;
  area:             string;
  extension:        string;
  empleado_recibe?: null;
  fecha_entregado?: null;
  status?:          string;
}
