// Generated by https://quicktype.io

export interface Destinatarios {
  destinatarios: Destinatario[],
}

export interface Destinatario {
  id:       number;
  nombre:   string;
  correo:   string;
  area:     string;
}
